### PR TITLE
Make multi-valued-CSVs work

### PR DESCRIPTION
**Pull request by mnelson4**
Contains work from https://github.com/eventespresso/eea-attendee-importer/pull/29
and https://github.com/eventespresso/eea-attendee-importer/pull/30

## Problem this Pull Request solves

Note: this is branched off `FET/payments` (because otherwise there would have been annoying conflicts, and add-ons isn't yet released), so this PR uses that as the base branch (to make it clearer what the changes are from that), so: if this gets merged before that branch, kool; if this gets merged **after** that branch, plz just merge it manually into master (as pressing "merge" below will merge it into a dead branch.)

This makes the sample CSV use commas for separate multi-valued questions. IMO that's better than bars like in EE3. CSV creatos just need to put the entire cell's value in quotes. Check out the sample CSV in this PR to see what I'm talking about (and yes we'll document it). Anyone feel free to disagree with me on whether this is best.

Also, this just trims the answer values so whitespace won't bork matching them up with the answer options in the DB.

## How has this been tested

* [ ] Create a multi-valued question (checkbox or multi-select) with values "1", "2", ... "6". 
* Add it to a question group 
* and add that question group to an event.
* Import the "ee3-attendee-importer-sample.csv" and map the "Answers (optional)" CSV column to the newly-made question. 
* Import the registrations. 
* Check on the registration details page that their answers to the newly-created question should be populated correctly
* [ ]  Do tests from https://github.com/eventespresso/eea-attendee-importer/pull/29 (recursively)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tn3rb** [comment]
I've approved the code review because technically there is nothing wrong with it, however, re:

> This makes the sample CSV use commas for separate multi-valued questions. IMO that's better than bars like in EE3. CSV creatos just need to put the entire cell's value in quotes. Check out the sample CSV in this PR to see what I'm talking about (and yes we'll document it). Anyone feel free to disagree with me on whether this is best.

I would argue that the pipes are better because there is far less chance of that conflicting with the values given for an answer. I have seen many cases where user sites have crazy multi-paragraph long answer options for questions complete with a host of common grammar symbols like periods, question marks... and commas. 

**plz get Josh to sign off on this change before proceeding**

**Comment by mnelson4** [comment]
> I would argue that the pipes are better because there is far less chance of that conflicting with the values given for an answer.

Oh that's a good point. Yeah if someone has an question option that's "Yes, please", then that won't work. So maybe pipes would be better.

@josh what would you think is the best way for a cell to contain an answer to a multi-valued question (like checkbox or multi-select)?

**Comment by joshfeck** [comment]
I agree that pipes would be better in this case, unless there's a compelling reason to not use pipes, then we should probably stick with what was done in EE3 in this case

**Comment by mnelson4** [comment]
Ok pipes it is! BTW this isn't exactly like EE3 though- EE3 used a single column for all answers, and you needed to use a double-pipe to separate answers for different questions etc. In this one each column can be assigned a question, and each answer option is separated by pipes.

**Comment by mnelson4** [comment]
Merging because the tree structure of these prs was getting confusing.
Merged into https://github.com/eventespresso/eea-attendee-importer/pull/23

**Pull request merged**
